// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class Activities
    {
        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public int FkActivityCategoryId { get; set; }
        public DateTime ActivityDate { get; set; }
        public int FkSpeakerId { get; set; }
        public string ActivityPlace { get; set; }
        public string ActivityImage { get; set; }
        public DateTime ActivityBookStartTime { get; set; }
        public DateTime ActivityBookEndTime { get; set; }
        public byte ActivityAge { get; set; }
        public int ActivitySalePrice { get; set; }
        public int ActivityOriginalPrice { get; set; }
        public string ActivityDescription { get; set; }
        public int FkActivityStatusId { get; set; }

        public virtual ActivityCategories FkActivityCategory { get; set; }
        public virtual ActivityStatuses FkActivityStatus { get; set; }
        public virtual Speakers FkSpeaker { get; set; }
    }
}