// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class ActivityCategories
    {
        public ActivityCategories()
        {
            Activities = new HashSet<Activities>();
        }

        public int ActivityCategoryId { get; set; }
        public string ActivityCategoryName { get; set; }

        public virtual ICollection<Activities> Activities { get; set; }
    }
}