// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class Coupons
    {
        public Coupons()
        {
            CouponSendings = new HashSet<CouponSendings>();
        }

        public int CouponId { get; set; }
        public int FkCouponCategoryId { get; set; }
        public string CouponName { get; set; }
        public string CouponDescription { get; set; }
        public string CouponCode { get; set; }
        public int MinimumPurchaseAmount { get; set; }
        public int DiscountType { get; set; }
        public int DiscountValue { get; set; }
        public DateTime StartDate { get; set; }
        public bool? EndType { get; set; }
        public int? EndDays { get; set; }
        public DateTime? EndDate { get; set; }
        public int? PersonMaxUsage { get; set; }
        public int? RequirementType { get; set; }
        public int? Requirement { get; set; }
        public int? FkRequiredProjectTagId { get; set; }
        public bool? Status { get; set; }

        public virtual CouponCategories FkCouponCategory { get; set; }
        public virtual ProjectTags FkRequiredProjectTag { get; set; }
        public virtual ICollection<CouponSendings> CouponSendings { get; set; }
    }
}