// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class CustomizedMaterials
    {
        public CustomizedMaterials()
        {
            CustomizedOrdersCustomizedEdgeProtectionNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomizedEyeletNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomizedRearNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomizedToeNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomizedTongueNavigation = new HashSet<CustomizedOrders>();
            ShoesGroups = new HashSet<ShoesGroups>();
        }

        public int ShoesmaterialId { get; set; }
        public string MaterialName { get; set; }

        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomizedEdgeProtectionNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomizedEyeletNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomizedRearNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomizedToeNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomizedTongueNavigation { get; set; }
        public virtual ICollection<ShoesGroups> ShoesGroups { get; set; }
    }
}