// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class CustomizedOrders
    {
        public int CustomizedId { get; set; }
        public string CustomizedNumber { get; set; }
        public int? CustomizedShoesId { get; set; }
        public int? FkForMemberCustomizedId { get; set; }
        public int? CustomizedEyelet { get; set; }
        public int? CustomizedEdgeProtection { get; set; }
        public int? CustomizedRear { get; set; }
        public int? CustomizedTongue { get; set; }
        public int? CustomizedToe { get; set; }
        public string Remark { get; set; }
        public DateTime? OrderCreateTime { get; set; }
        public DateTime? OrderEditTime { get; set; }

        public virtual CustomizedMaterials CustomizedEdgeProtectionNavigation { get; set; }
        public virtual CustomizedMaterials CustomizedEyeletNavigation { get; set; }
        public virtual CustomizedMaterials CustomizedRearNavigation { get; set; }
        public virtual CustomizedShoesPo CustomizedShoes { get; set; }
        public virtual CustomizedMaterials CustomizedToeNavigation { get; set; }
        public virtual CustomizedMaterials CustomizedTongueNavigation { get; set; }
        public virtual Members FkForMemberCustomized { get; set; }
    }
}