// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class LogisticsCompanies
    {
        public LogisticsCompanies()
        {
            Orders = new HashSet<Orders>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string LogisticsDescription { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
    }
}