// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class Privileges
    {
        public Privileges()
        {
            FkLevel = new HashSet<MembershipLevels>();
        }

        public int PrivilegeId { get; set; }
        public string PrivilegeName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<MembershipLevels> FkLevel { get; set; }
    }
}