// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class ProductGroups
    {
        public int ProductGroupId { get; set; }
        public string FkProductId { get; set; }
        public int FkColorId { get; set; }
        public int FkSizeId { get; set; }
        public int Qty { get; set; }

        public virtual ColorCategories FkColor { get; set; }
        public virtual Products FkProduct { get; set; }
        public virtual SizeCategories FkSize { get; set; }
    }
}