// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class ProjectTags
    {
        public ProjectTags()
        {
            Coupons = new HashSet<Coupons>();
            Discounts = new HashSet<Discounts>();
        }

        public int ProjectTagId { get; set; }
        public string ProjectTagName { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime ModifiedAt { get; set; }
        public bool? Status { get; set; }

        public virtual ICollection<Coupons> Coupons { get; set; }
        public virtual ICollection<Discounts> Discounts { get; set; }
    }
}