// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class ReservationStatuses
    {
        public ReservationStatuses()
        {
            OneToOneReservations = new HashSet<OneToOneReservations>();
        }

        public int ReservationId { get; set; }
        public string ReservationStatusDescription { get; set; }

        public virtual ICollection<OneToOneReservations> OneToOneReservations { get; set; }
    }
}