// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class ShoesPictures
    {
        public int ShoesPictureId { get; set; }
        public string ShoesPictureUrl { get; set; }
        public int FkShoesPictureProductId { get; set; }

        public virtual CustomizedShoesPo FkShoesPictureProduct { get; set; }
    }
}