// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class SizeCategories
    {
        public SizeCategories()
        {
            ProductGroups = new HashSet<ProductGroups>();
        }

        public int SizeId { get; set; }
        public string SizeName { get; set; }

        public virtual ICollection<ProductGroups> ProductGroups { get; set; }
    }
}