// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class Staffs
    {
        public int StaffId { get; set; }
        public string Name { get; set; }
        public byte? Age { get; set; }
        public bool? Gender { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public DateTime? Birthday { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime? DueDate { get; set; }
        public int FkPermissionsId { get; set; }
        public int FkTitleId { get; set; }
        public int FkDepartmentId { get; set; }
        public string ConfirmCode { get; set; }

        public virtual Departments FkDepartment { get; set; }
        public virtual StaffPermissions FkPermissions { get; set; }
        public virtual JobTitles FkTitle { get; set; }
    }
}