// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class Suppliers
    {
        public int SupplierId { get; set; }
        public string SupplierCompanyName { get; set; }
        public bool? HasCertificate { get; set; }
        public string SupplyMaterial { get; set; }
        public int? SupplierCompanyPhone { get; set; }
        public string SupplierCompanyEmail { get; set; }
        public string SupplierCompanyAddress { get; set; }
        public int? SupplierCompanyNumber { get; set; }
        public DateTime? SupplierStartDate { get; set; }
    }
}