// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexService.Models
{
    public partial class Type
    {
        public Type()
        {
            CartItems = new HashSet<CartItems>();
            OrderItems = new HashSet<OrderItems>();
            Orders = new HashSet<Orders>();
            PointHistories = new HashSet<PointHistories>();
            PointManage = new HashSet<PointManage>();
        }

        public int TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PointHistories> PointHistories { get; set; }
        public virtual ICollection<PointManage> PointManage { get; set; }
    }
}