// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class CartItems
    {
        public int CartItemId { get; set; }
        public int fk_CardId { get; set; }
        public int fk_Type { get; set; }
        public int ProductId { get; set; }
        public string Description { get; set; }
        public int Qty { get; set; }

        public virtual ShoppingCarts CartItem { get; set; }
        public virtual Type fk_TypeNavigation { get; set; }
    }
}