// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class CouponSendings
    {
        public int SendingId { get; set; }
        public int fk_CouponId { get; set; }
        public int? fk_MemberId { get; set; }
        public DateTime SentDate { get; set; }
        public bool RedemptionStatus { get; set; }
        public DateTime? RedeemedDate { get; set; }

        public virtual Coupons fk_Coupon { get; set; }
        public virtual Members fk_Member { get; set; }
    }
}