// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class Customized_materials
    {
        public Customized_materials()
        {
            CustomizedOrdersCustomized_EdgeProtectionNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomized_EyeletNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomized_RearNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomized_ToeNavigation = new HashSet<CustomizedOrders>();
            CustomizedOrdersCustomized_TongueNavigation = new HashSet<CustomizedOrders>();
            ShoesGroups = new HashSet<ShoesGroups>();
        }

        public int Shoesmaterial_Id { get; set; }
        public string material_Name { get; set; }

        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomized_EdgeProtectionNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomized_EyeletNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomized_RearNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomized_ToeNavigation { get; set; }
        public virtual ICollection<CustomizedOrders> CustomizedOrdersCustomized_TongueNavigation { get; set; }
        public virtual ICollection<ShoesGroups> ShoesGroups { get; set; }
    }
}