// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class JobTitles
    {
        public JobTitles()
        {
            Staffs = new HashSet<Staffs>();
        }

        public int TitleId { get; set; }
        public string TitleName { get; set; }
        public int? fk_StaffPermissions { get; set; }

        public virtual ICollection<Staffs> Staffs { get; set; }
    }
}