// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class MemberPoints
    {
        public MemberPoints()
        {
            PointHistories = new HashSet<PointHistories>();
        }

        public int MemberPointsId { get; set; }
        public int PointSubtotal { get; set; }
        public int fk_MemberId { get; set; }

        public virtual Members fk_Member { get; set; }
        public virtual ICollection<PointHistories> PointHistories { get; set; }
    }
}