// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class pay_statuses
    {
        public pay_statuses()
        {
            orders = new HashSet<orders>();
        }

        public int Id { get; set; }
        public string pay_status { get; set; }

        public virtual ICollection<orders> orders { get; set; }
    }
}