// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class Products
    {
        public Products()
        {
            ProductGroups = new HashSet<ProductGroups>();
            ProductImgs = new HashSet<ProductImgs>();
            ProjectTagItems = new HashSet<ProjectTagItems>();
        }

        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductMaterial { get; set; }
        public string ProductOrigin { get; set; }
        public int? UnitPrice { get; set; }
        public int SalesPrice { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public bool? Status { get; set; }
        public bool LogOut { get; set; }
        public string Tag { get; set; }
        public int fk_ProductSubCategoryId { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime EditTime { get; set; }

        public virtual ProductSubCategories fk_ProductSubCategory { get; set; }
        public virtual ICollection<ProductGroups> ProductGroups { get; set; }
        public virtual ICollection<ProductImgs> ProductImgs { get; set; }
        public virtual ICollection<ProjectTagItems> ProjectTagItems { get; set; }
    }
}