// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class ProjectTagItems
    {
        public int fk_ProjectTagId { get; set; }
        public string fk_ProductId { get; set; }

        public virtual Products fk_Product { get; set; }
    }
}