// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class ShoesGroups
    {
        public int ShoesGroupId { get; set; }
        public int fk_ShoesMainId { get; set; }
        public int fk_OptionId { get; set; }
        public int fk_MaterialId { get; set; }
        public int fk_ShoesColorId { get; set; }
        public string Remark { get; set; }

        public virtual Customized_materials fk_Material { get; set; }
        public virtual ShoesChooses fk_Option { get; set; }
        public virtual ShoesColorCategories fk_ShoesColor { get; set; }
        public virtual CustomizedShoesPo fk_ShoesMain { get; set; }
    }
}