// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class ShoppingCarts
    {
        public int CartId { get; set; }
        public int fk_MemberID { get; set; }

        public virtual Members fk_Member { get; set; }
        public virtual CartItems CartItems { get; set; }
    }
}