// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class Speakers
    {
        public Speakers()
        {
            Activities = new HashSet<Activities>();
            OneToOneReservations = new HashSet<OneToOneReservations>();
        }

        public int SpeakerId { get; set; }
        public string SpeakerName { get; set; }
        public string SpeakerPhone { get; set; }
        public int fk_SpeakerFieldId { get; set; }
        public string SpeakerImg { get; set; }
        public int? fk_SpeakerBranchId { get; set; }
        public string SpeakerDescription { get; set; }
        public bool SpeakerVisible { get; set; }

        public virtual Branches fk_SpeakerBranch { get; set; }
        public virtual SpeakerFields fk_SpeakerField { get; set; }
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual ICollection<OneToOneReservations> OneToOneReservations { get; set; }
    }
}