// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class Type
    {
        public Type()
        {
            CartItems = new HashSet<CartItems>();
            PointHistories = new HashSet<PointHistories>();
            PointManage = new HashSet<PointManage>();
            orderItems = new HashSet<orderItems>();
            orders = new HashSet<orders>();
        }

        public int TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual ICollection<PointHistories> PointHistories { get; set; }
        public virtual ICollection<PointManage> PointManage { get; set; }
        public virtual ICollection<orderItems> orderItems { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}